This is a combination of 10 commits.

diff --git a/src/bin/db-snapshot b/src/bin/db-snapshot
--- a/src/bin/db-snapshot
+++ b/src/bin/db-snapshot
@@ -13,7 +13,7 @@
 # ---------------------------------------------------------------------------
 usage() {
   cat <<- EOF
-	$(basename $0) <parameters>
+	$(basename $0) <parameters> [action]
 	
 	Clones an Oracle database from an ASM based storage snapshot.
 	
@@ -27,24 +27,31 @@ usage() {
 	1GB of memory. Enough hugepages must be available if the source database
 	also uses hugepages.
 	
-	The controlfile and spfile must be backed up in the sourcedir (i.e. using
-	RMAN autobackup) as they are used to re-generate parameter files and the
-	new controlfile.
+	$(basename $0) should run as user 'oracle' and must have password-less
+	ssh access from the copy to the source host.
 	
 	Parameters:
-	  -d - debug (switch to temp directory before quitting)
-	  -s - startup database (normal) after creation
+	  -c <configfile>   - read settings from <configfile>
+	  -D                - debug (switch to temp directory before quitting)
+	  -s                - startup database (normal) after creation
+	  --srv <host>      - set source DB hostname
+	  --src <sid>       - specify source database sid
+	  --tgt <sid>       - specify target  database sid
+	  --cmd <cmd>       - specify snapshot refresh command/script
+	  --sga <size>      - specify target sga size
+	  --pga <size>      - specify target pga size
+	Actions:
+	  stop       - stop source database, unmount ASM diskgroups
+	  prep       - run the prepare stage on the source host
+	  finalize   - run the finalize stage on the source host
+	  clone      - run the cloning stage on the target host
+	  <default>  - run entire cloning cycle
 	
-	  --orahome <dir>   - use <dir> as ORACLE_HOME instead of default
-	  --ctrlfile <file> - use this controlfile backup to restore database
-	  --datadest        - datafile destination (default /oradata)
-	  --redodest        - redolog destination (default=datadest)
-	  --tempdest        - tempfile destination (default=datadest)
-	  --archdest        - archivelog destination (default=datadest)
-	  --tempsize        - Use this size (MB) instead of original temp size
-	  --sgatarget       - Use this sgatarget (MB) instead of default (768)
-	  --pgatarget       - Use this pgatarget (MB) instead of default (256)
+	The command specified with --cmd should have the instructions to create/update
+	a snapshot on some kind of storage array or other cloning facility.
 	
+	Example:
+	  $(basename $0) --src demo --tgt clone --cmd /usr/local/bin/snaprefresh
 	
 	EOF
 }
@@ -52,6 +59,8 @@ usage() {
 #============================================================================
 # Initialization - Logging - Etc.
 # ---------------------------------------------------------------------------
+
+debug() { cd $WORKDIR && bash ; }
 die() { echo "$(basename $0): [die] $@" >&2 ; exit 10 ;}
 err() { echo "$(basename $0): [err] $@" ; exit 20 ;}
 
@@ -64,6 +73,9 @@ esac
 readonly WORKDIR=$(mktemp -d)
 cleanup() { rm -rf $WORKDIR ; }
 trap cleanup INT TERM HUP EXIT
+
+readonly SWAPDIR=/var/tmp/db-snapshot
+mkdir -p $SWAPDIR || die "cannot make SWAPDIR"
 
 unset ORACLE_SID
 unset ORACLE_HOME
@@ -79,7 +91,7 @@ sqlheader=$(printf "set heading off\nset feedback off\nset verify off\nwhenever 
 sql()    { printf "$sqlheader\n$@\n" | $ORACLE_HOME/bin/sqlplus -L -S / as sysdba; }
 sqlasm() { printf "$sqlheader\n$@\n" | $ORACLE_HOME/bin/sqlplus -L -S $ASMUSER/$ASMPASS@$ASMCONNECT as sysasm; }
 
-cleanup_src() {
+resetbackup() {
   export ORACLE_SID=$SRCSID
   cat <<- EOF > $WORKDIR/cleanup.sql
 	SET SERVEROUTPUT ON
@@ -87,11 +99,10 @@ cleanup_src() {
 	  A NUMBER;
 	BEGIN
 	  SELECT COUNT(status) INTO A FROM v\$backup where status='ACTIVE';
-	  -- DBMS_OUTPUT.PUT_LINE('Backup mode ' || A);
-	  if(A>0) THEN
+	  IF(A>0) THEN
 	    DBMS_OUTPUT.PUT_LINE('Cleanup: Ending backup mode ');
 	    EXECUTE IMMEDIATE('alter database end backup');
-	  end if;
+	  END IF;
 	END;
 	/
 	exit;
@@ -182,15 +193,15 @@ getpfile() {
   echo retrieving init.ora
   SPFILE=$(sql "select value from v\$parameter where name='spfile';" | awk 'NF>0 {print $NF}')
   test -n "$SPFILE" || die "spfile required"
-  sql "CREATE PFILE='$WORKDIR/init.ora' FROM SPFILE='$SPFILE';"
+  sql "CREATE PFILE='$SWAPDIR/init.ora' FROM SPFILE='$SPFILE';"
 }
 
 getctrlfile() {
   export ORACLE_SID=$SRCSID
   echo retrieving trace.sql
-  sql "ALTER DATABASE BACKUP CONTROLFILE TO TRACE AS '$WORKDIR/trace.sql';" || return 10
+  sql "ALTER DATABASE BACKUP CONTROLFILE TO TRACE AS '$SWAPDIR/trace.sql';" || return 10
   echo retrieving control.bkup
-  sql "alter database backup controlfile to '$WORKDIR/control.bkup';"       || return 10
+  sql "alter database backup controlfile to '$SWAPDIR/control.bkup';"       || return 10
 }
 
 getdisks() {
@@ -209,7 +220,7 @@ getdisks() {
 beginbackup() {
   export ORACLE_SID=$SRCSID
   echo Starting hot backup mode on $ORACLE_SID
-  sql "select max(sequence#) from v\$log;" | awk 'NF>0 {print $NF}' > $WORKDIR/beginseq
+  sql "select max(sequence#) from v\$log;" | awk 'NF>0 {print $NF}' > $SWAPDIR/beginseq
   sql "alter system checkpoint;"            || return $?
   sql "alter system switch logfile;"        || return $?
   sql "alter database begin backup;"        || return $?
@@ -226,19 +237,19 @@ endbackup() {
   echo Ending hot backup mode on $ORACLE_SID
   sql "alter database end backup;" || return 10
   sleep 1
-  sql "select current_scn from v\$database;" | awk 'NF>0 {print $NF}' > $WORKDIR/scn
+  sql "select current_scn from v\$database;" | awk 'NF>0 {print $NF}' > $SWAPDIR/scn
   sql "alter system switch logfile;" || return $?
   sql "alter system switch logfile;" || return $?
-  sql "select max(sequence#) from v\$log;" | awk 'NF>0 {print $NF}' > $WORKDIR/endseq
+  sql "select max(sequence#) from v\$log;" | awk 'NF>0 {print $NF}' > $SWAPDIR/endseq
 }
 
 copylogs() {
   export ORACLE_SID=$SRCSID
-  read bseq < $WORKDIR/beginseq
-  read eseq < $WORKDIR/endseq
-  echo copying archivelogs between sequence ${bseq:-unset} and ${eseq:-unset} on $ORACLE_SID
+  read bseq < $SWAPDIR/beginseq
+  read eseq < $SWAPDIR/endseq
   cat <<- EOF > $WORKDIR/copyfiles.sql
 	SET SERVEROUTPUT ON
+	PROMPT copying archivelogs between sequence ${bseq:-unset} and ${eseq:-unset} on $ORACLE_SID
 	DECLARE
 	  FULLNAME VARCHAR2(513);
 	  DIRNAME  VARCHAR2(513);
@@ -251,9 +262,9 @@ copylogs() {
 	  FROM v\$archived_log a where status='A' and sequence# between ${bseq:-0} and ${eseq:-0};
 	BEGIN
 	  SELECT substr(name,1,instr(name,'/',-1,1)) INTO DIRNAME
-	  FROM v\$archived_log where status='A' and sequence#=(select max(sequence#) from v\$archived_log);
+	  FROM v\$archived_log where status='A' and sequence#=(select max(sequence#) from v\$archived_log where status='A');
 	  EXECUTE IMMEDIATE('CREATE OR REPLACE DIRECTORY archdir as ''' || DIRNAME || '''');
-	  EXECUTE IMMEDIATE('CREATE OR REPLACE DIRECTORY workdir as ''' || '$WORKDIR' || '''');
+	  EXECUTE IMMEDIATE('CREATE OR REPLACE DIRECTORY workdir as ''' || '$SWAPDIR' || '''');
 	  OPEN cur;
 	  LOOP
 	    FETCH cur into FULLNAME,BASENAME,THREAD,SEQ,RID;
@@ -269,7 +280,7 @@ copylogs() {
 	/
 	exit;
 	EOF
-  sql @copyfiles.sql
+  sql @$WORKDIR/copyfiles.sql
 }
 
 getdiskgroups() { 
@@ -360,20 +371,39 @@ tempfile() {
   sql @$WORKDIR/tempfile.sql
 }
 
-dosrc() {
+src() {
   trap cleanup_src INT TERM HUP EXIT
-  doprep       || die "Prepare SRC failed"
+  prep         || die "Prepare SRC failed"
   $SNAPCOMMAND || die "Snapshot command failed"
-  dofinalize   || die "Finalize SRC failed"
+  finalize     || die "Finalize SRC failed"
+}
+
+arch() {
+  tar --remove-files -cf - -C ${SWAPDIR%/*} ${SWAPDIR##*/}
+}
+
+safe() {
+  trap reset INT TERM HUP EXIT
+  sleep 120 < /dev/null &>/dev/null &
+}
+
+reset() {
+  self=/tmp/$(basename $0)
+  scp -q $0 ${SRCHOST}:${self}                               || err "scp script transfer failed"
+  timeout 60 ssh -qT ${SRCHOST} $self --src $SRCSID resetbackup || die "Resetbackup failed"
 }
 
 remote() {
   self=/tmp/$(basename $0)
-  p="--src $SRCSID --cmd $SNAPCOMMAND"
-  scp -q $0 ${SRCHOST}:${self}                || err "scp script to $SRCHOST failed"
-  timeout 300 ssh -qT ${SRCHOST} $self $p dosrc  || err "Remote commands failed"
-  scp -q ${SRCHOST}:/tmp/package.tar $WORKDIR || err "scp tar failed"
-  tar -x -C $WORKDIR -f $WORKDIR/package.tar  || err "untar failed"
+  scp -q $0 ${SRCHOST}:${self}                               || err "scp script transfer failed"
+
+#  ssh -qT ${SRCHOST} $self --src $SRCSID safe
+
+  timeout 60 ssh -qT ${SRCHOST} $self --src $SRCSID prep     || die "Prepare failed"
+  cmd $SNAPCOMMAND                                           || die "Snapshot failed"
+  timeout 60 ssh -qT ${SRCHOST} $self --src $SRCSID finalize || die "Finalize failed"
+  timeout 60 ssh -qT ${SRCHOST} $self arch | tar -x --strip-components=1 -C $WORKDIR -f - \
+   || die "remote tar failed"
 }
 
 # --- wrappers
@@ -387,12 +417,14 @@ cmd() {
   return ${PIPESTATUS[0]}
 }
 
-dostop() {
+stop() {
   cmd stopdb      || die "Can't stop copy database"
   cmd asm_unmount || die "Can't unmount copy diskgroup(s)"
 }
 
-doprep() {
+prep() {
+  rm -rf $SWAPDIR/*
+  (
   avail               || die "Database $SRCSID not open"
   cmd purgelogs       || die "Purging archivelogs failed"
   cmd getpfile        || die "Get init.ora failed"
@@ -403,9 +435,10 @@ doprep() {
     hot)  cmd beginbackup || die "Hot backup mode failed" ;;
     *)    die "Unknown method $METHOD" ;;
   esac
+  ) 2>&1
 }
 
-dofinalize() {
+finalize() {
   case ${METHOD,,} in
     cold) cmd startsrc  || echo "Starting source DB failed, continue..." ;;
     hot)  cmd endbackup || die "End backup failed"
@@ -413,10 +446,9 @@ dofinalize() {
           ;;
     *)    die "Unknown method $METHOD" ;;
   esac
-  tar -cf /tmp/package.tar -C $WORKDIR . || die "Creating tar archive failed"
 }
 
-doclone() {
+clone() {
   cmd dgrename    || die "Rename ASM diskgroup failed"
   cmd asm_mount   || die "Can't mount copy diskgroup(s)"
   cmd mkinitora   || die "Create init.ora failed"
@@ -432,13 +464,12 @@ doclone() {
 }
 
 doall() {
-  dostop
+  stop
   remote
-  doclone
+  clone
 }
 
 testsql () { 
-  echo here
   export ORACLE_SID=$SRCSID
   sql "select max(sequence#) from v\$log;" | awk 'NF>0 {print $NF}'
 }
@@ -447,20 +478,21 @@ testsql () {
 # Main section - parsing options etc
 # ---------------------------------------------------------------------------
 
-while getopts ":hc:d-:s" OPT; do
+while getopts ":hc:D-:s" OPT; do
   case "$OPT" in
     -) [[ "${!OPTIND:0:1}" == "-" ]] && die "no parameter for option ${OPTARG}"
        case "${OPTARG}" in
-         srv) SRCHOST=${!OPTIND} ; ((OPTIND++)) ;;
-         src) SRCSID=${!OPTIND} ; ((OPTIND++)) ;;
-         tgt) TGTSID=${!OPTIND} ; ((OPTIND++)) ;;
+         srv) SRCHOST=${!OPTIND}     ; ((OPTIND++)) ;;
+         src) SRCSID=${!OPTIND}      ; ((OPTIND++)) ;;
+         tgt) TGTSID=${!OPTIND}      ; ((OPTIND++)) ;;
+         oh)  ORACLE_HOME=${!OPTIND} ; ((OPTIND++)) ;;
          cmd) SNAPCOMMAND=${!OPTIND} ; ((OPTIND++)) ;;
-         sga) sgatarget=${!OPTIND} ; ((OPTIND++)) ;;
-         pga) pgatarget=${!OPTIND} ; ((OPTIND++)) ;;
+         sga) sgatarget=${!OPTIND}   ; ((OPTIND++)) ;;
+         pga) pgatarget=${!OPTIND}   ; ((OPTIND++)) ;;
          *)   die "unknown long option $OPTARG" ;;
        esac ;;
     c) conf="$OPTARG" ;;
-    d) debug=Y ;;
+    D) DEBUG=Y ;;
     s) start=Y ;;
  \?|h) usage ; exit ;;
   esac
@@ -474,28 +506,30 @@ shift $(expr $OPTIND - 1)
 : ${ASMPASS:=outrun}
 : ${ASMPREFIX:=COPY}
 : ${PURGELOGS:=Y}
-: ${sgatarget:=512m}
+: ${sgatarget:=768m}
 : ${pgatarget:=256m}
 : ${SRCHOST:=localhost}
 
-# Mandatory
-# SRCHOST=outrun01
-# SRCSID=DEMO
-# TGTSID=SNAP
-# SNAPCOMMAND="/usr/test/bin/isnap"
+test -n "$ORACLE_HOME" \
+  || export ORACLE_HOME=$(awk -v src=${SRCSID:-none} -v tgt=${TGTSID:-none} -F: '$1==src || $1==tgt {print $2 ; exit }' /etc/oratab)
 
-export ORACLE_HOME=$(awk -v src=${SRCSID:-none} -v tgt=${TGTSID:-none} -F: '$1==src || $1==tgt {print $2 ; exit }' /etc/oratab)
+export ORACLE_HOME
 export ORAENV_ASK=NO
 export PATH=$ORACLE_HOME/bin:$PATH
 export ORACLE_BASE=$(orabase)
 
 ACTION=$1 ; shift
 case $ACTION in
-  stop)  dostop  ;;
-  prep)  doprep  ;;
-  fin*)  dofinalize ;;
-  clone) doclone ;;
+  safe)  safe ;;
+  reset) reset ;;
+  arch)  arch  ;;
+  stop)  stop  ;;
+  prep)  prep  ;;
+  fin*)  finalize ;;
+  clone) clone ;;
   "")    doall   ;;
   *)     $ACTION ;;
 esac
+
+# test -z "$DEBUG" && debug
 
